// import disini memungkinkan untuk memproyeksikan direktori sehingga dapat memudahkan untuk mengimpor modul.
import React from 'react';
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

// cons(Konstanta) disini mengambil nama dengan bernama children
const Layout = ({children, title}) => {
    return (
        <div>
            {/* Disini digunakan untuk sub ICON dan Judul*/}
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/goplay.ico"/>
            </Head>
            {/* Disini juga dapat digunakan untuk Judul sebagai Header */}
            <header className="bg-slate-900 py-10 mb-10">
                <Link href="/">
                    <a>
                        <h1 className="text-6xl text-center text-amber-400">{title}</h1>
                    </a>
                </Link>
            </header>

            {/* Disini terdapat container untuk memasukan data pokemon yang ada di pokeapi.co ke dalam website ini */}
            <main className="container mx-auto">
                {children}
            </main>

            {/* Disini terdapat footer yang dapat dilihat untuk pembuatan creator dari website ini */}
            <footer className="flex justify-center items-center mt-10">
                <a
                    className="flex flex-col"
                    href="https://www.linkedin.com/in/luthfi-al-fikri-5785b42aa"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                     Powered by{' '}
                    <Image src="/instamon.png" alt="Pokemon Logo" width={72} height={85}/>Luthfi Al Fikri
                </a>
            </footer>
        </div>
    );
};

export default Layout;
